### ISSUE TITLE
Impose force layout

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#12]
It would possibly be useful to be able to drag points around, then hit a button that uses the current positions as the starting point for a force-optimised layout (possibly with the Y-positions constrained, see #10 )

**Comment by kitchensjn** [comment]
![tskit_arg_visualizer with reheat](https://github.com/kitchensjn/tskit_arg_visualizer/assets/40303683/52462dfd-938d-46c5-ae09-23b5717e3bb5)

I could see something like that being really useful, though I think we would need to play around with the forces used to position the nodes. Often, it takes a bit of dragging to get the nodes where they look best. In the GIF, I run the initially build, rearrange the nodes, and then restart the force simulation from the new positions. This can create more tangling than you had in your rearranged positions (as you can see in the GIF), but there may be a way to limit how far a node can move from its starting position.

One positioning pattern that I always do with "ortho" style ARGs is move recombination nodes directly above their child node, unless their child is also a recombination node. The force simulation generally can't recreate that positioning pattern as the nodes would prefer to push away from one another rather than be stacked.

The biggest use case of something like this would be reordering the tip nodes. The tip order is set by the first tree in the tree sequence, which is not necessarily the most optimal ordering for untangling the ARG.

**Comment by hyanwong** [comment]
It would possibly be useful to allow graphviz to set the initial positions for the other nodes too (for complex graphs). YMMV.

**Comment by kitchensjn** [comment]
Testing out using graphviz to handle initial positioning in this a separate branch ([here](https://github.com/kitchensjn/tskit_arg_visualizer/tree/graphviz_positions)). It's hard to tell how helpful it is for untangling; as you pointed out, it probably best suited to some but not all graphs.

**Comment by hyanwong** [comment]
Neat, thanks for looking into this. It's really appreciated

**Comment by kitchensjn** [comment]
I am reworking how the visualizer takes in graphviz node positioning. It would be better for graphviz positions to be pre-calculated and then passed into the `D3ARG` object rather than this process occurring during the initialization of the D3ARG object. By splitting up these steps, users can pass in whatever positions they want, whether that be from graphviz, hand-selected, or some other calculation. I'm working on two optional position inputs for the `D3ARG` initialization, `fixed_x_positions` and `starting_x_positions` depending on if users want the positions to be updated by the force simulation.

**Comment by hyanwong** [comment]
I think this can probably be closed now?

**Comment by kitchensjn** [comment]
Yeah I think we've gotten what we want out of this.
