### ISSUE TITLE
Plot a subset of points

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#13]
For huge ARGs, like the sc2ts ARG (1.4 million nodes), we can only display a small subset of nodes in a viz like this. Nevertheless, that can be *extremely* useful (see the last set of supplementary figures at https://www.biorxiv.org/content/10.1101/2023.06.08.544212v1). It would be really useful to be able to specify a subset of points to plot.

There are also various ways you could imagine creating a subset of points to plot by expanding outwards from a smaller number of nodes (e.g. take 2 samples, expand to find their common ancestor(s) either in a specific tree or in all trees. It is unclear to me if something like this would be built-in to a visualiser, or be a separate routine to create a set of nodes, which then get passed in.

**Comment by kitchensjn** [comment]
If you wanted to have the whole ARG in the background but to focus on a select set of nodes/edges, something quick like this could work:

<img width="500" alt="Screen Shot 2023-06-20 at 5 29 03 PM" src="https://github.com/kitchensjn/tskit_arg_visualizer/assets/40303683/8d8540a2-24e8-463e-92bd-038192cc09cf">

I can add a parameter to pass a list of nodes of interest into the drawing function. For the above ARG, I passed `subset_nodes=[0,1,2,8,10,11,14,15]`. If both the edge's parent and child are in the list, then the edge gets colored. This method doesn't solve the problem when there are too many nodes to coherently display. Most useful if you wanted to focus on a specific region without losing the broader context.

We previously talked about the collapsible force layout for interactively showing a subset of nodes. This method is generally used with trees rather than graphs. If we want to apply this to the ARG, we would need to determine how we want the graph to collapse, especially around recombination nodes which add a unique challenge. Another snag is that I am currently setting the y-axis position of the nodes in Python before sending everything to D3 for plotting. The collapsible force layout would require dynamic positioning so would need to be handled in a different way. I'll continue to look into this!

**Comment by hyanwong** [comment]
Just returning to this after thinking about huge ARGs. I wonder if a neat thing would be to pass in the tree sequence and a single node ID, and to be able to right-click (or equivalent) on that node to be able to add *connected nodes* into the viz, and so on, building up a graph viz by expanding outwards.

How doable might this be @kitchensjn ? Would it help in your case of visualising parts of large tree sequences?

**Comment by kitchensjn** [comment]
I've been thinking about a single node view similar to as you describe but without the interactivity. The biggest hurdle to work through with the visualization you described is updating the y-position of the nodes once more nodes have been included in the graph; this would all need to be done in JS rather than Python.

**Comment by kitchensjn** [comment]
So I've taken another stab at this and think I've come up with something. Very much based off of the figures in the sc2ts paper, I've added a draw function where you select a node and a number of degrees of connections and it draws the local connections around that node.

<img width="500" alt="local_node" src="https://github.com/kitchensjn/tskit_arg_visualizer/assets/40303683/3b31e3e0-1698-4d5f-89e7-ef9e2d6eff22">

Here, I've selected the recombination node 29/30 and degree 3, so nodes that are above or below in three connections or less. One nice feature from the sc2ts paper that is missing here are the short dashed connections to nodes not included in the subset. I'm working out a way to include those now.

Importantly, this is not any node within three degrees of the focal node, only those that are above and below; this may not be the most convenient way to define this but was easiest to first implement.

**Comment by hyanwong** [comment]
Neat. Thanks for this @kitchensjn. I will have a play next week. It would be interesting to see if I can roughly reproduced the sc2ts plots.

**Comment by kitchensjn** [comment]
Lastest commit includes this new function with some documentation (cedc206).

```
def draw_node(
    self,
    node,
    width=500,
    height=500,
    degree=1,
    y_axis_labels=True
):
"""Draws a subgraph of the D3ARG using D3.js by sending a custom JSON object to visualizer.js

Parameters
----------
node : int
    Node ID that will be central to the subgraph
width : int
    Width of the force layout graph plot in pixels (default=500)
height : int
    Height of the force layout graph plot in pixels (default=500)
degree : int
    Number of degrees above and below the central node to include in the subgraph (default=1)
y_axis_labels : bool
    Includes labelled y-axis on the left of the figure (default=True)
"""
```

This function is very similar to the standard draw(), but you need to provide a node ID which will be the center of the subgraph. At the moment, it also doesn't have quite as many optional styling parameters; graphs are always drawn with tree_highlighting=False, y_axis_scale="rank", edge_type="line", variable_edge_width=False, and include_underlink=True.

**Comment by kitchensjn** [comment]
Also, I added the missing edges

<img width="500" alt="local_node_with_edges" src="https://github.com/kitchensjn/tskit_arg_visualizer/assets/40303683/2244a04e-e8e9-473d-9f96-07d60b76edfb">

Dashed lines coming into the top of the node are for missing parent edges and below is missing child edges. The number at the end of the dashed line tells you how many edges of that type are missing for each node. This was a lot easier and hopefully cleaner than trying to position a bunch of these dashed edges around the nodes per missing edge.

**Comment by kitchensjn** [comment]
You can update the styles of individual nodes and edges with the `set_node_styles()` and `set_edge_colors()` functions. These are really just wrappers, styles are stored in pandas.DataFrames so the values could also be updated directly if that would be easier for certain scenarios. This is manual process and does require that you know what nodes/edges should be altered. 

```
import msprime
import random
import json
import tskit_arg_visualizer

d3arg = tskit_arg_visualizer.D3ARG.from_ts(ts=ts)

d3arg.set_node_styles([
    {"id":0,"fill":"pink"},
    {"id":7,"fill":"pink"}
])
d3arg.set_edge_colors({
    0:"pink",
    7:"pink"
})

d3arg.draw_node(29, degree=6)
```

<img width="500" alt="" src="https://github.com/kitchensjn/tskit_arg_visualizer/assets/40303683/d75189f5-9f07-46da-b2f6-dfa1e7941bd2">

**Comment by kitchensjn** [comment]
Latest commit (cf69820) adds `y_axis_scale` parameter to `draw_node()`. Same as in the original `draw()`, you can plot using "rank", "time", or "log_time".

**Comment by hyanwong** [comment]
Funky. Thanks @kitchensjn !

**Comment by kitchensjn** [comment]
<img width="500" alt="original D3ARG" src="https://github.com/kitchensjn/tskit_arg_visualizer/assets/40303683/c4744072-d82b-4bca-a5d5-6a875665a4c9">

<img width="500" alt="discretized D3ARG" src="https://github.com/kitchensjn/tskit_arg_visualizer/assets/40303683/e911cd40-7937-4520-b8b1-c638bca266c8">

Another simplification concept that may be relevant to @russcd as well. Here, the top image is the original ARG on a log_time scale and the bottom image is the corresponding discretized time ARG. I started with a set of time bins, grouped all connected nodes that fall into the same time bin into a single node, then updated the edge table to account for all of the newly collapsed nodes. In the bottom image, the collapsed nodes are shown in white and the uncollapsed are the standard green. This collapsed version of the ARG cannot be stored as a tskit.TreeSequence because the collapsed nodes don't play nicely with the edge interval paradigm of tskit (more generally it isn't suitable for calling individual trees), but it does simplify the structure in an algorithmic way. I could see this working interactively as well, say as you zoom in the time bins get smaller so more nodes/connections become visible. My spaghetti code does all of the simplifications in Python given a set of bins then passes it to JS, so binning is a static property. Giving users the ability to Zoom would require this to be done in JS, Pyodide, or on a backend server.

**Comment by hyanwong** [comment]
Presumably we can close this issue now, and maybe reopen a different one about drawing "summary" nodes like the version you illustrated in the comment above?

**Comment by kitchensjn** [comment]
Cool, happy to close and reopen a separate issue for the "summary" nodes as that seems like a big rabbit hole.
