### ISSUE TITLE
Add a licence

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#25]
I would love to use this on some of the tskit tutorial pages. It would be helpful if (a) there was a licence on this repo (e.g. MIT or whatever) and (b) there were some instructions for installation (ideally I could do something like

```
pip install git+https://github.com/kitchensjn/tskit_arg_visualizer
```

Which requires a setup.py file. I realise this might not be a priority in the development phase of the visualiser, though.

**Comment by kitchensjn** [comment]
I believe that I've gotten pip install working from the setup branch using the following command:

`pip install git+https://github.com/kitchensjn/tskit_arg_visualizer.git@setup`

The package structure has changed slightly. To call the package, you use:

- `import tskit_arg_visualizer` (instead of `from visualizer import visualizer`)
- `tskit_arg_visualizer.D3ARG()` (instead of `visualizer.D3ARG()`)

I've updated the [README.md](https://github.com/kitchensjn/tskit_arg_visualizer/blob/setup/README.md) to reflect these changes and added an MIT license to the repo. Let me know if you have any trouble getting it installed. Once I run a few more tests this coming week, I'll merge this branch into main.

**Comment by hyanwong** [comment]
This looks fine for me, and looks really good. Thanks for those changes @kitchensjn, this is fantastic!

**Comment by kitchensjn** [comment]
You can now install from main branch

`pip install git+https://github.com/kitchensjn/tskit_arg_visualizer.git`
