### ISSUE TITLE
Sample nodes with different symbol (or colour?)

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#30]
It can be helpful to distinguish sample and non-sample nodes. It is possible to have internal samples (i.e. sample nodes with children), so it's not always the case that tips === samples. In the SVG viz we use squares rather than circles for sample nodes. I guess this might be possible with the D3js viz too?

**Comment by kitchensjn** [comment]
`d3arg.draw(...,node_size="XXXX", node_symbol="XXXX", sample_node_symbol="XXXX")` now gives the user options to control the sizing and the symbols used for nodes within the visualizer. Symbols are now SVG paths (rather than circles) and you can use any of the options from [d3.symbols](https://d3js.org/d3-shape/symbol) catalog. Technically, you should be able to pass in your own path string, but I have not tested that. By default, `node_symbol="d3.symbolCircle", sample_node_symbol="d3.symbolCircle"`, so all nodes match. Also, important note from the commit - "if you don't want nodes at all, you can set `node_size=0` but this removes your ability to draw the nodes (and edges) around."

**Comment by hyanwong** [comment]
This is fab, thanks @kitchensjn.

In the oath view, you could imaging wanting to highlight recombination vs common ancestor nodes somehow, but that's probably easiest done by colour rather than shape. And I guess highlighting using colours can be done via css?

**Comment by kitchensjn** [comment]
Ah good question! I've added a class to each node that corresponds with its tskit flag. Node flags can be styled individually using CSS:

```
.flag131072 {
    fill: orange;
    stroke: blue;
}

.flag0 {
    fill: purple;
    stroke: green;
}
```

<image alt="ARG with separately styled nodes" src="https://github.com/kitchensjn/tskit_arg_visualizer/assets/40303683/8ad07cdf-d6e5-4902-b118-37f6d01eb289" width="400px">

Currently, `d3arg.draw()` doesn't have a parameter for altering this; you'll need to alter the CSS file or add your own. I'm wondering how much of the styling should be controlled by external CSS files versus inline styling, especially if we want the ability to customize. I'll reopen this issue.

**Comment by kitchensjn** [comment]
I've updated this on the branch new_styles_structuring. Rather than the list of dictionaries, I've stored the nodes, edges, and breakpoints info as a `pandas.DataFrame`. This introduces another dependency but seems to be a more stable and scalable way of storing this. Each row in the node dataframe now also includes styling for that node. This means that users can now individually control these stylings, such as changing the fill of node 4 to orange and stroke to blue without having to modify the CSS file. I've added some additional class functions to handle this. I'd be interested to hear if you think that this is the correct direction for this. Definitely more customizability but requires keeping track of more information. For static figures, most of these styling changes could also be added after the fact by outputting an SVG and styling it in Illustrator or an equivalent program.

**Comment by hyanwong** [comment]
I don't have a strong feeling about this, but it can be useful to "inline" style changes as well as override them through CSS. I assume that's what the style entry in the data frame does.

It's presumably useful to also allow changes in style using CSS, as that makes it easy to apply a style to a whole set of nodes (e.g. all of the sample nodes).

**Comment by kitchensjn** [comment]
I believe that this set up will give you that flexibility. Nodes can be styled using the the inline styles which are pulled from the data frame, but then they also have classes, such as "node flag1" which can be used to style groups of nodes together. CSS class stylings will override the inline styles.

**Comment by kitchensjn** [comment]
Closing this now that we have the pandas.DataFrame with columns for node and edge styling. We may want to separate the node table from the styling table if they start to get too big, but keeping them together for now.
