### ISSUE TITLE
Issues getting the visualiser to work in jupyterlab

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#47]
I'm having difficulty getting the latest tskit_arg_visualizer to work on Jupyterlab (v 4.0.0). It was working fine with my installed JupyterLab until the latest `tskit_arg_visualizer ` update. Now I'm just getting a blank output (no error messages being printed, but nothing being drawn to screen either). Has awnythgin changed recently?

**Comment by kitchensjn** [comment]
I believe that I've tracked this down to an issue with declaring the following variable in JS:

`const stepBefore = d3.line().curve(d3.curveStepBefore);`

In previous versions, I used `var` instead of `const`, so I have reverted that in the latest commit to GitHub.

Out of curiosity, are you using Safari or another web browser? [StackOverflow](https://stackoverflow.com/questions/40091136/cant-create-duplicate-variable-that-shadows-a-global-property) post about this issue. I'm not sure why it only comes up in JupyterLab and not the other ways.

Please let me know if that does not fix it for you!

**Comment by hyanwong** [comment]
Thanks for the quick reply and fix (it now works). I was using the jupyterlab-desktop version on OS X, which I suspect uses webkit (i.e. the Safari toolkit).
