### ISSUE TITLE
Initialise an interactive plot from a saved JSON object

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#49]
It would be nice to be able to pass initial x/y positions from a saved JSON object into a call to `d3arg.draw`, so that the same positions can be used but with different labelling, etc.

**Comment by kitchensjn** [comment]
This has taken me a little while to think through. I think that the cleanest way to add this functionality is to have a way of initializing a D3ARG object from a JSON. Then you'll have access to all of the D3ARG methods, like `set_node_labels()`. When initializing from a JSON, I'm setting the node positions as fixed so that they don't slide around on their own when plotted.

I've started to play around with this on the linked branch. The code needs to be cleaned up and redocumented as the class initialization method has changed to account for the multiple possible inputs (this is also new to me, so there very well could be a better code structure to handle this).

**Comment by kitchensjn** [comment]
#58 should now allow for this functionality, through the following example:

```
import json
import tskit_arg_visualizer

arg_json = json.load(open("example.json", "r"))
d3arg = tskit_arg_visualizer.D3ARG.from_json(json=arg_json)
```

Note that from_json takes in a loaded JSON, not the file path. Then you should have access to any of the methods associated with a D3ARG object like modifying node labels and drawing.
