### ISSUE TITLE
Specifying a starting order for samples

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#53]
Is it possible to specify a fixed order for the sample tips?

**Comment by kitchensjn** [comment]
At the moment, no... but definitely something that I want to add.

I haven't yet implemented it because I've been debating reworking the tip positioning altogether. Currently, the ordering is set when you initialize the D3ARG object. This feels a bit limiting and unnecessary at this step. But sticking with this method, I can add a D3ARG method, like `change_tip_order(order=[...])`, which would update the position of the tips within the node attribute. Would something like that accomplish your needs? It might get cumbersome if you are trying out a bunch of different tip orders.

Alternatively, node order could be passed as a parameter in the `draw()` method. I think this feels a bit more natural, but would require some reworking.

**Comment by kitchensjn** [comment]
I decided to bite the bullet and update how the nodes are being positioned along the x-axis. This was actually very helpful for evenly distributing after dragging so it aligned well. On the linked GitHub branch, the sample order can be changed when drawing:

```
import msprime
import random
import tskit_arg_visualizer

ts = msprime.sim_ancestry(
    samples=5,
    recombination_rate=1e-8,
    sequence_length=3_000,
    population_size=10_000,
    record_full_arg=True,
    random_seed=random.randint(0,10000)
)

d3arg = tskit_arg_visualizer.D3ARG(ts=ts)
d3arg.draw(width=1000, height=500, edge_type="ortho", sample_order=[0,1,2,3,4])
```

<img width="1100" alt="Screenshot 2023-10-20 at 12 08 10 PM" src="https://github.com/kitchensjn/tskit_arg_visualizer/assets/40303683/78362afb-1f16-444e-9302-12dc35d3c512">

`sample_order` is an ordered list of sample nodes. Samples not included in this list are appended to the end of the list in the order that they appear in the first tree in the tree sequence. Planning to merge with main soon!
