### ISSUE TITLE
Margins issue: X-axis labels cut off in online notebooks

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#62]
When embedding a viz in a JupyterBook notebook (and presumably in other versions of Jupyter Notebooks), there is a lot of whitespace around the plot, but even so, something is cutting off the X axis labels:

<img width="706" alt="Screenshot 2023-11-09 at 13 34 01" src="https://github.com/kitchensjn/tskit_arg_visualizer/assets/4699014/5cfd7c23-5446-49ff-9da2-9c4e9e263e2e">

It would be nice to be able to specify smaller margins but not cut off labels. I guess the margin thing might be some setting in the notebook display rather than the visualizer itself.

**Comment by kitchensjn** [comment]
This should actually be fixed by the latest commit (ff4963d). I had some bad styling on the HTML SVG object (padding-top: 10px) that was shifting the visualization down but then not resizing the SVG bounds accordingly. I've removed that padding as it wasn't really needed with the rest of the whitespace.

**Comment by hyanwong** [comment]
Yep, thanks. I can confirm that this is fixed. Is there a way to remove the extra white margin around the plot (e.g. at the bottom) too?
<img width="483" alt="Screenshot 2023-11-09 at 16 17 31" src="https://github.com/kitchensjn/tskit_arg_visualizer/assets/4699014/f9c6cccb-cf17-43a5-ab22-43454f3cc2b4">

**Comment by kitchensjn** [comment]
There's padding on the d3arg class div which contains everything; this could be decreased or removed entirely. Right now the padding is used to center the figure within the whitespace when the controls dashboard isn't visible. If you completely remove the padding on the d3arg class, it will look like there's extra whitespace at the top since the controls dashboard is hidden there.
