### ISSUE TITLE
Ability to add a title to the viz

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#72]
I'm showing a few separate ARGs, at different levels of simplification. It would be useful to be able to add a title to each plot. Perhaps if there is a title, the buttons at the top can be right-aligned, and the title can go in the middle, where the buttons previously were?

**Comment by kitchensjn** [comment]
Added a title parameter for both `draw()` and `draw_node()`. There aren't additional styling options just to keep things simple for now. Titles should be relatively short as I haven't implemented any text wrapping. I didn't end up moving the buttons as I placed the title within the SVG so that it will be saved with the figure, whereas the buttons are in a separate div from the SVG. This is something that I can come back to in the future if it's bothersome.
